### ISSUE TITLE
Help request made on xda

### ISSUE THREAD

**Issue by lopestom** [usernamealreadytaken55/twrp_sungworld_Tablet_DL_2811#1]
I think you know how to do and have knowledge to install TWRP files.
You requested help here: [error: recovery.img too large](https://forum.xda-developers.com/t/error-recovery-img-too-large.4530455/)

You can download img files for test here:
14.2 MB =>> https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3722321901

13.5 MB =>> https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3722139993

More files for tests and maybe better than those above about only 8.48 MB each img file: https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811

**Comment by usernamealreadytaken55** [comment]
Thank you for helping me out!
Firstly, may I ask how did you manage to build those 8.48MB images?  Kinda new to this

So, I tried booting and flashing all of those, they behave the same: black screen for a few seconds and
reboots into normal mode (and its overwritten by the stock recovery).

Problem with the device tree, then?

**Comment by lopestom** [comment]
> Thank you for helping me out! Firstly, may I ask how did you manage to build those 8.48MB images? Kinda new to this
> 
> So, I tried booting and flashing all of those, they behave the same: black screen for a few seconds and reboots into normal mode (and its overwritten by the stock recovery).
> 
> Problem with the device tree, then?

I not know if your device should unlock the bootloader. If you can do......
The img with 8,48MB maybe have mounting errors because the tool I used in Linux is not good.
Use AIK (Windows or Linux) to unpack img and repack. Now look the size of file.

The DT maybe is not good or maybe good because compiling img file.
Same question to yours files about stock recovery.img so if you can upload file here for some analisys.....
Let me the information with adb-fastboot: `fastboot getvar all`

**Comment by usernamealreadytaken55** [comment]
Yeah, unlocked it with 'fastboot flashing unlock'

fastboot getvar all

```
(bootloader) 	max-download-size: 0x8000000
(bootloader) 	partition-size:userdata: 32000000
(bootloader) 	partition-type:userdata: ext4
(bootloader) 	partition-size:cache: 10000000
(bootloader) 	partition-type:cache: ext4
(bootloader) 	partition-size:system: c0000000
(bootloader) 	partition-type:system: ext4
(bootloader) 	partition-size:metadata: 23c0000
(bootloader) 	partition-type:metadata: raw data
(bootloader) 	partition-size:nvdata: 2000000
(bootloader) 	partition-type:nvdata: ext4
(bootloader) 	partition-size:tee2: 500000
(bootloader) 	partition-type:tee2: raw data
(bootloader) 	partition-size:tee1: 500000
(bootloader) 	partition-type:tee1: raw data
(bootloader) 	partition-size:frp: 100000
(bootloader) 	partition-type:frp: raw data
(bootloader) 	partition-size:expdb: a00000
(bootloader) 	partition-type:expdb: raw data
(bootloader) 	partition-size:logo: 800000
(bootloader) 	partition-type:logo: raw data
(bootloader) 	partition-size:para: 80000
(bootloader) 	partition-type:para: raw data
(bootloader) 	partition-size:keystore: 800000
(bootloader) 	partition-type:keystore: raw data
(bootloader) 	partition-size:secro: 600000
(bootloader) 	partition-type:secro: raw data
(bootloader) 	partition-size:oemkeystore: 200000
(bootloader) 	partition-type:oemkeystore: raw data
(bootloader) 	partition-size:recovery: 1000000
(bootloader) 	partition-type:recovery: raw data
(bootloader) 	partition-size: boot : 1000000
(bootloader) 	partition-type: boot : raw data
(bootloader) 	partition-size:lk: 100000
(bootloader) 	partition-type:lk: raw data
(bootloader) 	partition-size:seccfg: 40000
(bootloader) 	partition-type:seccfg: raw data
(bootloader) 	partition-size:protect2: a00000
(bootloader) 	partition-type:protect2: ext4
(bootloader) 	partition-size:protect1: a00000
(bootloader) 	partition-type:protect1: ext4
(bootloader) 	partition-size:nvram: 500000
(bootloader) 	partition-type:nvram: raw data
(bootloader) 	partition-size:proinfo: 300000
(bootloader) 	partition-type:proinfo: raw data
(bootloader) 	partition-size:preloader: 40000
(bootloader) 	partition-type:preloader: raw data
(bootloader) 	off-mode-charge: 1
(bootloader) 	warranty: no
(bootloader) 	unlocked: yes
(bootloader) 	secure: no
(bootloader) 	kernel: lk
(bootloader) 	product: ELINK8321_TB_N
(bootloader) 	version-preloader: 
(bootloader) 	version: 0.5
```

[recovery.zip](https://github.com/usernamealreadytaken55/twrp_sungworld_Tablet_DL_2811/files/10253999/recovery.zip)

**Comment by lopestom** [comment]
> Yeah, unlocked it with 'fastboot flashing unlock'
> 
> fastboot getvar all
> 
> ```
> (bootloader) 	partition-size:recovery: 1000000
> (bootloader) 	partition-type:recovery: raw data

> (bootloader) 	off-mode-charge: 1
> (bootloader) 	warranty: no
> (bootloader) 	unlocked: yes
> (bootloader) 	secure: no
> (bootloader) 	kernel: lk
> (bootloader) 	product: ELINK8321_TB_N
> (bootloader) 	version-preloader: 
> (bootloader) 	version: 0.5
> ```

That's great! 
My question about the size of the recovery partition has been cleared.
Note that `partition-size:recovery: 1000000` has a Hex size of 0x1000000 which refers to the DEC of 16777216 or 16.777216 MB

So we have more space to work with and thus test more img files.
What I can't understand is that the img files I'm compiling are coming with version 3.7.0_9 even using the twrp-7.1 branch.

Now I can put more information and settings related to the tablet device.
I need correct resolution and rotation in the screen (0,90,180,270,360).

**Comment by usernamealreadytaken55** [comment]
Not really sure if thats what you need
```
mDefaultViewport=DisplayViewport{valid=true, displayId=0, orientation=0, logicalFrame=Rect(0, 0 - 600, 1024), physicalFrame=Rect(0, 0 - 600, 1024), deviceWidth=600, deviceHeight=1024}

mDefaultViewport=DisplayViewport{valid=true, displayId=0, orientation=1, logicalFrame=Rect(0, 0 - 1024, 600), physicalFrame=Rect(0, 0 - 1024, 600), deviceWidth=1024, deviceHeight=600}

mDefaultViewport=DisplayViewport{valid=true, displayId=0, orientation=2, logicalFrame=Rect(0, 0 - 600, 1024), physicalFrame=Rect(0, 0 - 600, 1024), deviceWidth=600, deviceHeight=1024}

mDefaultViewport=DisplayViewport{valid=true, displayId=0, orientation=3, logicalFrame=Rect(0, 0 - 1024, 600), physicalFrame=Rect(0, 0 - 1024, 600), deviceWidth=1024, deviceHeight=600}
```

**Comment by lopestom** [comment]
Try this img file
https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811

**Comment by lopestom** [comment]
> I need correct resolution and rotation in the screen (0,90,180,270,360).

I need correct rotation in the screen (0,90,180,270,360). How you see the screen in your tablet (android system)?
how you see stock recovery screen?
Maybe you can upload any photo?!

**Comment by usernamealreadytaken55** [comment]
> Try this img file https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811

Doesn't work

```
target reported max download size of 134217728 bytes
FAILED (remote: size too large)
```

**Comment by usernamealreadytaken55** [comment]
> > I need correct resolution and rotation in the screen (0,90,180,270,360).
> 
> I need correct rotation in the screen (0,90,180,270,360). How you see the screen in your tablet (android system)? how you see stock recovery screen? Maybe you can upload any photo?!

Portrait mode, just like a phone
Same applies to recovery

**Comment by lopestom** [comment]
> > Try this img file https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811
> 
> Doesn't work
> 
> ```
> target reported max download size of 134217728 bytes
> FAILED (remote: size too large)
> ```

Well, according your `get var` information the size of recovery partition is much than 13MB.
So I don't know how to help.

**Comment by usernamealreadytaken55** [comment]
> > > Try this img file https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811
> > 
> > 
> > Doesn't work
> > ```
> > target reported max download size of 134217728 bytes
> > FAILED (remote: size too large)
> > ```
> 
> Well, according your `get var` information the size of recovery partition is much than 13MB. So I don't know how to help.

Don't worry, it's ok 
I really, really appreciate your help
Just wondering, the fact that any of those images worked with `fastboot boot` probably indicates an issue with the device tree, right? if so, think I'm gonna start all over again.

I mean, those images should boot regardless of those issues regarding the recovery partition

**Comment by lopestom** [comment]
> 

What??
The `fastboot boot recovery.img` maybe is not good to your device!
Use `fastboot flash recovery.img` so img file is TWRP - rename if you want.

**Comment by usernamealreadytaken55** [comment]
> > 
> 
> What?? The `fastboot boot recovery.img` maybe is not good to your device! Use `fastboot flash recovery recovery.img` so img file is TWRP - rename if you want.
> 
> If have any problem so TWRP not start - use SPFT to install stock recovery.img or enter in the bootloader mode - fastboot/bootloader and use stock recovery.img to install.

I tried flashing all of them. The latest one reported the size limit error I mentioned. Was just curious if 'fastboot boot' would work.

**Comment by lopestom** [comment]
Other test with new img file.
https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3731595600

I'll upload new img files for test soon. But these files is with PORT.

**Comment by usernamealreadytaken55** [comment]
> Other test with new img file. https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3731595600
> 
> I'll upload new img files for test soon. But these files is with PORT.
> 
> You can test recoveryTWRP3.1.1-Tablet_DL_2811.zip unzipping img file. https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811

Sorry for the delay
Once again, thank you for your help!
Well, the first image flashes normally, but booting into recovery freezes the device (stuck at boot logo).
The another one does not flash at all 

`target reported max download size of 134217728 bytes
sending 'recovery' (16684 KB)...
OKAY [  0.671s]
writing 'recovery'...
FAILED (remote: size too large)
finished. total time: 0.678s
`

**Comment by lopestom** [comment]
> > Other test with new img file. https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3731595600
> > I'll upload new img files for test soon. But these files is with PORT.
> > You can test recoveryTWRP3.1.1-Tablet_DL_2811.zip unzipping img file. https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/Tablet_DL_2811
> 
> Sorry for the delay Once again, thank you for your help! Well, the first image flashes normally, but booting into recovery freezes the device (stuck at boot logo). The another one does not flash at all
> 
> `target reported max download size of 134217728 bytes sending 'recovery' (16684 KB)... OKAY [ 0.671s] writing 'recovery'... FAILED (remote: size too large) finished. total time: 0.678s `

The first file made with twrp-7.1 branch. I not know about problem because made with your recovery.img version
https://github.com/lopestom/twrp_sungworld_Tablet_DL_2811#android-device-tree-for-dl-tablet_dl_2811-tablet_dl_2811

Maybe your device need more than recovery.img?? Maybe make the disable verity-verify in the boot.img??
Maybe modify TW_THEME := portrait_hdpi to other mode so good??!

_We_/You need more informations an trying all.
